name: Build and Render Quarto

on:
  push:
    paths:
      - "**.qmd"
      - "_quarto.yml"
      - ".github/workflows/render.yml"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: quarto-dev/quarto-actions/setup@v2
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::knitr
      - name: Render site
        run: quarto render diamonds_plot.qmd
      - name: Upload site
        uses: actions/upload-pages-artifact@v3

